export const services = [
  { slug:'hpc-cluster', title:'HPC Cluster', icon:'▣', summary:'High performance computing resources for analysis, modeling, and simulation.', tasks:'Run a computation', body:'Use shared compute resources for larger analyses, simulations, batch jobs, and research workflows that need more power than a laptop.' },
  { slug:'jupyterhub', title:'JupyterHub', icon:'⌘', summary:'Interactive Python, R, and notebook environments for teaching and research.', tasks:'Use JupyterHub', body:'JupyterHub provides browser-based notebooks for courses, workshops, and research. Faculty guide: https://fandm-college.github.io/jupyterhub-guide/' },
  { slug:'globus', title:'Globus', icon:'☁', summary:'Reliable data transfer and sharing for research files.', tasks:'Transfer data', body:'Globus supports managed, resumable transfers for large research data sets. Faculty guide: https://fandm-college.github.io/globus/' },
  { slug:'storage', title:'Data Storage', icon:'◎', summary:'Storage options for research data, project work, and collaboration.', tasks:'Store research data', body:'Research Computing can help choose storage locations for active projects, data sharing, and longer-term research needs.' },
  { slug:'rstudio', title:'RStudio', icon:'▥', summary:'Statistical computing and R workflows in a managed environment.', tasks:'Analyze in RStudio', body:'RStudio gives students and researchers a familiar interface for R, packages, data analysis, visualization, and reproducible reports.' },
  { slug:'webwork', title:'WebWork', icon:'𝑊', summary:'Online homework and assessment for quantitative courses.', tasks:'Use WebWork', body:'WebWork supports online problem sets, automated grading, and course-based mathematics and quantitative assignments.' },
  { slug:'national-resources', title:'External & National Resources', icon:'◎', summary:'ACCESS, Jetstream2, Open Science Grid, and other national cyberinfrastructure.', tasks:'Use national resources', body:'Research Computing can help identify external computing resources, prepare proposals or allocations, and connect projects to ACCESS, Jetstream2, Open Science Grid, and related services.' },
  { slug:'consulting', title:'Research Consulting', icon:'☏', summary:'Project planning, workflow design, software, data, and computing guidance.', tasks:'Get expert help', body:'Schedule a consultation to discuss research computing needs, course support, data management, or available local and national resources.' }
];
