- name: Checkout
  uses: actions/checkout@v4

- name: Show current directory
  run: |
    pwd
    ls -lah

- name: Show package.json
  run: cat package.json

- name: Node version
  run: |
    node -v
    npm -v

- name: Install dependencies
  run: npm install

- name: Show install results
  run: |
    ls -lah
    ls -lah node_modules || true
    ls -lah node_modules/.bin || true
    npm list

- name: Build
  run: npx astro build